# The Letters of Marie Mancini

title: The Letters of Marie Mancini

# url is your gh-pages base, following the pattern: username.github.io
url: https://thecdil.github.io
# baseurl is your github repository's name prefixed with a /
baseurl: /mancini_source

# Collections
collections:
  letters:
    output: true

# Use Bootstrap (true, false)
bootstrap: true
# Use optional Bootstrap JS (true, false)
bootstrap-js: true
# Use JQuery Core
jquery: true
# Use fontawesome CDN (true, false)
fontawesome: false

# url to the shared assets folder on Digital
digital-assets: https://www.lib.uidaho.edu/assets