# The Letters of Marie Mancini

title: The Letters of Marie Mancini

# url is your gh-pages base, following the pattern: username.github.io
url: https://cdil.lib.uidaho.edu
# baseurl is your github repository's name prefixed with a /
baseurl: /mancini

# Collections
collections:
  letters:
    output: true

# set defaults
defaults:
  - scope:
      path: ""
      type: "letters"
    values:
      layout: "letter"

# Use Bootstrap (true, false)
bootstrap: true
# Use optional Bootstrap JS (true, false)
bootstrap-js: true
# Use JQuery Core
jquery: true
# Use fontawesome CDN (true, false)
fontawesome: true

# url to the shared assets folder on Digital
digital-assets: https://www.lib.uidaho.edu/assets

# url to the directory of images on Digital
digital-objects: https://www.lib.uidaho.edu/digital/objects/mancini